#!/usr/bin/perl

###########################################################
###########################################################
# This file was modified from a script in the Sockso project
# owned by Rod at http://sockso.pu-gh.com

# The directory that the bs-tester.jar file is stored in
use constant BS_TESTER_DIR => "/home/steven/bs-tester";
# Affects the behavior of start and stop.  If 1, start will
# do start-server.  If 0, start will do start-client.  Same
# for stop
use constant SERVER => 1;

#
###########################################################
###########################################################

use strict;

my $cmd = shift();

if ( $cmd eq "start" ) { start(); }
elsif ( $cmd eq "stop" ) { stop(); }
elsif ( $cmd eq "status" ) { status(); }
elsif ( $cmd eq "restart" ) { restart(); }
else { usage(); }

sub restart {
  stop();
  sleep 5;
  start();
}

sub start {
  my $pid = `ps ax | grep bs-tester.jar | grep -v grep`;
	$pid =~ s/^\s*(\d+) .*/$1/;

	if ( $pid ) {
		print "Already running\n"
	} else {
    if (SERVER) {
      start_server();
    } else {
      start_client();
    }
	}
}

sub stop {
	my $pid = `ps x | grep bs-tester.jar | grep -v grep`;
	$pid =~ s/^\s*(\d+) .*/$1/;

	if ( $pid ) {
		`kill $pid`;
	}
}

sub start_server {
	chdir( BS_TESTER_DIR );
	system( './run.sh -s > /dev/null 2>/dev/null &' );
}

sub start_client {
	chdir( BS_TESTER_DIR );
	system( './run.sh > /dev/null 2>/dev/null &' );
}

sub status {
	my $pid = `ps ax | grep bs-tester.jar | grep -v grep`;
	$pid =~ s/^\s*(\d+) .*/$1/;

	if ( $pid ) {
		print "Running\n"
	} else {
		print "Not running\n"
	}
}


sub usage {
	print <<EOF;

Usage: bs-tester (start|stop|restart|status)

EOF
}
